-- Generated by scripts/generate-seed.mjs from src/data — starting content for a fresh database.
-- Safe to re-run: existing rows are left alone.

-- Products
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('lobia', 'ENTRY 005', 'Lobia', 'Lobia', 'pulses', 'beans', 'India', 'whole', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 0) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('matar', 'ENTRY 006', 'Matar', 'Matar', 'pulses', 'peas', 'India', 'whole', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 1) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('kabuli-chana', 'ENTRY 007', 'Kabuli Chana', 'Kabuli Chana', 'pulses', 'chickpeas', 'India', 'whole', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 2) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('rajma', 'ENTRY 008', 'Rajma', 'Rajma', 'pulses', 'beans', 'India', 'whole', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 3) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('kala-chana', 'ENTRY 009', 'Kala Chana', 'Kala Chana', 'pulses', 'chickpeas', 'India', 'whole', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 4) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('chana-dal', 'ENTRY 010', 'Chana Dal', 'Chana Dal', 'pulses', 'dal', 'India', 'split', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 5) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('moong-sabut', 'ENTRY 011', 'Moong Sabut', 'Moong Sabut', 'pulses', 'whole', 'India', 'whole', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 6) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('moong-dhuli', 'ENTRY 012', 'Moong Dhuli', 'Moong Dhuli', 'pulses', 'dal', 'India', 'split', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 7) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('urad-sabut', 'ENTRY 013', 'Urad Sabut', 'Urad Sabut', 'pulses', 'whole', 'India', 'whole', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 8) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('ir64-silky-sortex-raw', 'ENTRY 014', 'Silky Sortex Raw IR64', 'IR64 Sortex', 'rice', 'non-basmati', 'India', 'raw, sortexed', array['Broken grades: 5% / 10% / 15% / 25% / 100%']::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 9) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('masuri-silky-sortex-raw', 'ENTRY 015', 'Silky Sortex Raw Masuri', 'Masuri Sortex', 'rice', 'non-basmati', 'India', 'raw, sortexed', array['Broken grades: 5% / 10% / 15% / 25%']::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 10) on conflict (id) do nothing;
insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values ('sona-masuri-steam', 'ENTRY 016', 'Steam Sona Masuri', 'Sona Masuri', 'rice', 'non-basmati', 'India', 'steam', array[]::text[], array[]::text[], array[]::text[], 'active', 'SOURCE VERIFIED', 11) on conflict (id) do nothing;

-- Testimonials (only when the table is empty)
insert into public.testimonials (name, location, quote, sort)
select * from (values
  ('Distributor', 'Retail supply partner, GCC', 'Consistent grain length and aroma, container after container — exactly what we need on our shelves.', 0),
  ('Wholesale Buyer', 'Import partner, East Africa', 'Documentation is always clean and complete, which keeps our customs clearance fast at the other end.', 1),
  ('Food Service Buyer', 'Distribution partner, South Asia', 'Responsive on quotes and flexible on volumes, from trial orders up to full container loads.', 2)
) as v (name, location, quote, sort)
where not exists (select 1 from public.testimonials);

-- Regions (only when the table is empty)
insert into public.regions (name, countries, lon, lat, map_label, sort)
select * from (values
  ('GCC', 'UAE, Saudi Arabia, Oman, Qatar, Kuwait, Bahrain', 46.7, 24.7, 'above', 0),
  ('East & North Africa', 'Kenya, Tanzania, Somalia, Egypt, Sudan', 32.5, 15.5, 'below', 1),
  ('South Asia', 'Sri Lanka, Bangladesh, Nepal, Maldives', 90.4, 23.8, 'below', 2),
  ('Southeast Asia', 'Indonesia, Malaysia, Vietnam, Thailand', 101.7, 3.1, 'above', 3),
  ('Europe', 'United Kingdom, Germany, Netherlands, France', 4.5, 51.9, 'above', 4),
  ('USA & Canada', 'United States, Canada', -74, 40.7, 'above', 5)
) as v (name, countries, lon, lat, map_label, sort)
where not exists (select 1 from public.regions);

-- Company settings
insert into public.settings (id, data) values (1, '{"email":"info@maheshricetrading.com","phone":"+971528186624","whatsapp":"971528186624","hours":"Sun – Fri, 9:00 AM – 6:00 PM","address":{"line1":"SMARK 2, Office 3","line2":"Ras Al Khor Industrial 2","city":"Dubai","country":"United Arab Emirates"},"social":{"instagram":"https://instagram.com/maheshricetrading","linkedin":"https://linkedin.com/company/mahesh-rice-trading","facebook":"https://facebook.com/maheshricetrading"},"mapEmbedSrc":"https://maps.google.com/maps?q=Ras%20Al%20Khor%20Industrial%202%2C%20Dubai%2C%20UAE&t=&z=13&ie=UTF8&iom=1&output=embed","licenseNumber":"1632113","trn":"105507496500003"}'::jsonb) on conflict (id) do nothing;
