// Builds supabase/seed.sql from the site's built-in data files, so the database starts with
// exactly what the site shows today. Run: node scripts/generate-seed.mjs
// The seed only inserts rows that don't exist yet — it never overwrites admin edits.
import { writeFileSync } from 'node:fs'
import { products } from '../src/data/products.js'
import { testimonials } from '../src/data/testimonials.js'
import { regions } from '../src/data/regions.js'
import { company } from '../src/data/company.js'
import { settingsFromCompany } from '../src/data/mapping.js'

const q = (v) => (v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const arr = (a) => `array[${a.map(q).join(', ')}]::text[]`

const lines = [
  '-- Generated by scripts/generate-seed.mjs from src/data — starting content for a fresh database.',
  '-- Safe to re-run: existing rows are left alone.',
  '',
  '-- Products',
  ...products.map(
    (p, i) =>
      `insert into public.products (id, entry, name, short_name, category, subcategory, origin, processing, specs, packaging, markets, status, verification, sort) values (${[
        q(p.id), q(p.entry), q(p.name), q(p.shortName), q(p.category), q(p.subcategory), q(p.origin), q(p.processing),
        arr(p.specs), arr(p.packaging), arr(p.markets), q(p.status), q(p.verification), i,
      ].join(', ')}) on conflict (id) do nothing;`,
  ),
  '',
  '-- Testimonials (only when the table is empty)',
  'insert into public.testimonials (name, location, quote, sort)',
  'select * from (values',
  testimonials.map((t, i) => `  (${q(t.name)}, ${q(t.location)}, ${q(t.quote)}, ${i})`).join(',\n'),
  ') as v (name, location, quote, sort)',
  'where not exists (select 1 from public.testimonials);',
  '',
  '-- Regions (only when the table is empty)',
  'insert into public.regions (name, countries, lon, lat, map_label, sort)',
  'select * from (values',
  regions.map((r, i) => `  (${q(r.name)}, ${q(r.countries)}, ${r.coords[0]}, ${r.coords[1]}, ${q(r.mapLabel ?? 'above')}, ${i})`).join(',\n'),
  ') as v (name, countries, lon, lat, map_label, sort)',
  'where not exists (select 1 from public.regions);',
  '',
  '-- Company settings',
  `insert into public.settings (id, data) values (1, ${q(JSON.stringify(settingsFromCompany(company)))}::jsonb) on conflict (id) do nothing;`,
  '',
]

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n'))
console.log(`seed.sql: ${products.length} products, ${testimonials.length} testimonials, ${regions.length} regions, settings`)
